### login
POST http://localhost:5000/login/login
Content-Type: application/json

{
        "email": "admin@admin.com",
        "password": "adminpsw"
}

### Logout
POST http://localhost:5000/login/logout


### get user by id
GET http://localhost:5000/users/60e399b5d18ab75ac0413bd3

### add user
POST http://localhost:5000/users/
Content-Type: application/json

{
        "username": "AMUGUS",
        "email": "user4@user.com",
        "password": "password"
}

### update user general info
PATCH http://localhost:5000/users/60e399b5d18ab75ac0413bd3
Content-Type: application/json

{
        "username": "usuario test principal modified",
        "email": "test2@test.com",
        "password": "password2342",
        "picture": "someURLmodified"
}

### update user general info
PATCH http://localhost:5000/users/password/60e399b5d18ab75ac0413bd3
Content-Type: application/json

{
        "email": "test2@test.com",
        "password": "newPassword123",
        "newPassword": "newPassword",
        "confirmPassword": "newPassword"
}

### delete user 
DELETE http://localhost:5000/users/60e8dd4399e3ea695c70ad37 

